"""
A setuptools based setup module for installing French CRS (Coreference Resolution System)
"""

from setuptools import setup, find_packages

setup(
    name='french-crs', 
    version='0.2', 
    description='French CRS is a coreference resolver for French trained by ANCOR corpus',
    url='https://github.com/mehdi-mirzapour/French-CRS',  
    author='Mehdi Mirzapour',
    author_email='mehdi.mirzapour@gmail.com', 
    classifiers=[  
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
    ],
    keywords='coreference resolution',  
    packages=find_packages(), 
    python_requires='>=3.7, <4',
    entry_points={
        'console_scripts': 'crs-resolver=command_line.crs_resolver:run_pipelines'
        },
    install_requires=[
        'appnope',
        'attrs',
        'backcall',
        'beautifulsoup4',
        'bleach',
        'blis',
        'bs4',
        'certifi',
        'chardet',
        'click',
        'cymem',
        'decorator',
        'defusedxml',
        'entrypoints',
        'et-xmlfile',
        'spacy',
        'idna',
        'scorch',
        'importlib-metadata',
        'ipykernel',
        'ipython',
        'ipython-genutils',
        'jdcal',
        'jedi',
        'Jinja2',
        'joblib',
        'jsonschema',
        'jupyter-client',
        'jupyter-core',
        'Keras-Preprocessing',
        'MarkupSafe',
        'mistune',
        'mock',
        'murmurhash',
        'nbconvert',
        'nbformat',
        'networkx',
        'stanza',
        'spacy_stanza',
        'notebook',
        'numpy',
        'openpyxl',
        'pandas',
        'python-docx',
        'pandocfilters',
        'parso',
        'stanza',
        'spacy_stanza',
        'pbr',
        'pexpect',
        'pickleshare',
        'plac',
        'preshed',
        'prometheus-client',
        'prompt-toolkit',
        'ptyprocess',
        'Pygments',
        'pyrsistent',
        'python-dateutil',
        'pytz',
        'pyzmq',
        'regex',
        'requests',
        'scikit-learn',
        'scipy',
        'Send2Trash',
        'six',
        'sklearn',
        'soupsieve',
        'terminado',
        'testpath',
        'thinc',
        'threadpoolctl',
        'tornado',
        'tqdm',
        'pathlib',
        'traitlets',
        'ufal.udpipe',
        'urllib3',
        'wasabi',
        'wcwidth',
        'webencodings',
        'xlrd',
        'zipp'
     ]
)
